baseurl = "hhttps://risal-shefin.github.io/"
theme = "hugo-geo2"
relativeURLs = false
languageCode = "en-us"
title = "Shefin's Blog"
disqusShortname = ""
paginate = 5

[taxonomies]
	tag = "tags"
	tutorial = "tutorials"

[params]
	showglobe = true

	favicon = "img/icon.jpg"
	
	analytics = "UA-158787337-1"

	email = "shefin.cse16@gmail.com"

	# Header Title for the main page
	header = "Some Random Writings"

	profilepic = "img/profile.png"
	
	title = "RISAL SHAHRIAR SHEFIN"
	subtitle = "PROGRAMMING BLOG"

	# Social buttons for sidebar
	# Each of these are optional
	[[params.socialbuttons]]
	faicon = "facebook"
	url = "https://www.facebook.com/shahriar.shefin"
	[[params.socialbuttons]]
	faicon = "github"
	url = "https://github.com/risal-shefin"
	[[params.socialbuttons]]
	faicon = "linkedin"
	url = "https://www.linkedin.com/in/risal-shahriar-shefin/"

	[[params.navlinks]]
	name = "About"
	url = "about/"
	
	[[params.navlinks]]
	name = "Blog"
	url = "post/"

	[[params.navlinks]]
	name = "Category"
	url = "tags/"
